/* ===== SPANISH A2 WORD BANK — 5 tiers x 100 = 500 ===== */
const WORDS_ES = {
1: [
["casa","집","la (여성)"],["ciudad","도시","la (여성)"],["comida","음식, 식사","la (여성)"],["dinero","돈","el (남성)"],["familia","가족","la (여성)"],
["trabajo","일, 직장","el (남성)"],["escuela","학교","la (여성)"],["tienda","가게, 상점","la (여성)"],["mercado","시장","el (남성)"],["playa","해변","la (여성)"],
["calle","거리, 길","la (여성)"],["coche","자동차","el (남성)"],["cocina","부엌, 요리","la (여성)"],["ventana","창문","la (여성)"],["puerta","문","la (여성)"],
["mesa","탁자, 식탁","la (여성)"],["silla","의자","la (여성)"],["camisa","셔츠","la (여성)"],["zapatos","신발","los (남성 복수)"],["verano","여름","el (남성)"],
["invierno","겨울","el (남성)"],["libro","책","el (남성)"],["agua","물","el (예외: 여성명사)"],["amigo","친구","el (남성)"],["hermano","형제","el (남성)"],
["hermana","자매","la (여성)"],["padre","아버지","el (남성)"],["madre","어머니","la (여성)"],["hijo","아들","el (남성)"],["hija","딸","la (여성)"],
["perro","개","el (남성)"],["gato","고양이","el (남성)"],["pan","빵","el (남성)"],["leche","우유","la (여성)"],["carne","고기","la (여성)"],
["fruta","과일","la (여성)"],["verdura","채소","la (여성)"],["huevo","계란","el (남성)"],["queso","치즈","el (남성)"],["sopa","수프","la (여성)"],
["arroz","쌀, 밥","el (남성)"],["pescado","생선","el (남성)"],["pollo","닭고기","el (남성)"],["vino","와인","el (남성)"],["cerveza","맥주","la (여성)"],
["ropa","옷","la (여성)"],["cama","침대","la (여성)"],["mano","손","la (예외: 여성명사)"],["ojo","눈","el (남성)"],["boca","입","la (여성)"],
["sala","거실","la (여성)"],["plaza","광장","la (여성)"],["noche","밤","la (여성)"],["luz","빛","la (여성)"],["flor","꽃","la (여성)"],
["nube","구름","la (여성)"],["lluvia","비","la (여성)"],["nieve","눈","la (여성)"],["tierra","땅","la (여성)"],["piedra","돌","la (여성)"],
["mujer","여자","la (여성)"],["carta","편지","la (여성)"],["palabra","단어","la (여성)"],["historia","이야기, 역사","la (여성)"],["cara","얼굴","la (여성)"],
["pierna","다리","la (여성)"],["cabeza","머리","la (여성)"],["manzana","사과","la (여성)"],["naranja","오렌지","la (여성)"],["sal","소금","la (여성)"],
["taza","찻잔","la (여성)"],["botella","병","la (여성)"],["llave","열쇠","la (여성)"],["papel","종이","el (남성)"],["reloj","시계","el (남성)"],
["tren","기차","el (남성)"],["barco","배","el (남성)"],["camino","길","el (남성)"],["sol","태양","el (남성)"],["viento","바람","el (남성)"],
["fuego","불","el (남성)"],["pájaro","새","el (남성)"],["caballo","말","el (남성)"],["hombre","남자","el (남성)"],["abuelo","할아버지","el (남성)"],
["país","나라","el (남성)"],["día","날, 하루","el (예외: 남성명사)"],["cuarto","방","el (남성)"],["espejo","거울","el (남성)"],["plato","접시","el (남성)"],
["vaso","잔","el (남성)"],["zapato","신발","el (남성)"],["sombrero","모자","el (남성)"],["pie","발","el (남성)"],["brazo","팔","el (남성)"],
["pelo","머리카락","el (남성)"],["oreja","귀","la (여성)"],["nariz","코","la (여성)"],["dedo","손가락","el (남성)"],["espalda","등","la (여성)"]
],
2: [
["trabajar","일하다","동사"],["viajar","여행하다","동사"],["empezar","시작하다","동사 (e→ie)"],["terminar","끝내다","동사"],["comprar","사다","동사"],
["vender","팔다","동사"],["aprender","배우다","동사"],["entender","이해하다","동사 (e→ie)"],["escribir","쓰다","동사"],["recordar","기억하다","동사 (o→ue)"],
["olvidar","잊다","동사"],["ayudar","돕다","동사"],["esperar","기다리다, 바라다","동사"],["llegar","도착하다","동사"],["salir","나가다, 외출하다","동사"],
["volver","돌아오다","동사 (o→ue)"],["conocer","(사람·장소를) 알다","동사"],["preferir","선호하다","동사 (e→ie)"],["dormir","자다","동사 (o→ue)"],["sentir","느끼다","동사 (e→ie)"],
["hablar","말하다","동사"],["comer","먹다","동사"],["beber","마시다","동사"],["vivir","살다","동사"],["leer","읽다","동사"],
["abrir","열다","동사"],["cerrar","닫다","동사 (e→ie)"],["correr","달리다","동사"],["caminar","걷다","동사"],["bailar","춤추다","동사"],
["cantar","노래하다","동사"],["cocinar","요리하다","동사"],["limpiar","청소하다","동사"],["lavar","씻다","동사"],["llevar","가지고 가다, 입다","동사"],
["traer","가져오다","동사"],["dejar","남기다, 그만두다","동사"],["poner","놓다","동사"],["pedir","요청하다, 주문하다","동사 (e→i)"],["contar","세다, 이야기하다","동사 (o→ue)"],
["jugar","놀다, (경기를) 하다","동사 (u→ue)"],["pensar","생각하다","동사 (e→ie)"],["querer","원하다, 사랑하다","동사 (e→ie)"],["poder","할 수 있다","동사 (o→ue)"],["deber","해야 한다","동사"],
["necesitar","필요하다","동사"],["buscar","찾다","동사"],["encontrar","발견하다, 만나다","동사 (o→ue)"],["usar","사용하다","동사"],["cambiar","바꾸다","동사"],
["nadar","수영하다","동사"],["escuchar","듣다","동사"],["mirar","보다","동사"],["entrar","들어가다","동사"],["subir","오르다","동사"],
["bajar","내리다","동사"],["pagar","지불하다","동사"],["enseñar","가르치다","동사"],["estudiar","공부하다","동사"],["preguntar","묻다","동사"],
["contestar","대답하다","동사"],["llamar","부르다","동사"],["tomar","잡다, 마시다","동사"],["desear","바라다","동사"],["creer","믿다","동사"],
["explicar","설명하다","동사"],["parar","멈추다","동사"],["descansar","쉬다","동사"],["levantar","들어올리다","동사"],["preparar","준비하다","동사"],
["romper","부수다","동사"],["arreglar","고치다","동사"],["crear","만들다","동사"],["dibujar","그리다","동사"],["pintar","칠하다","동사"],
["ganar","이기다, 벌다","동사"],["regresar","돌아가다","동사"],["quedar","남다","동사"],["sacar","꺼내다","동사"],["mover","움직이다","동사 (o→ue)"],
["abrazar","껴안다","동사"],["llorar","울다","동사"],["gritar","소리치다","동사"],["aceptar","받아들이다","동사"],["decidir","결정하다","동사"],
["mejorar","개선하다","동사"],["crecer","자라다","동사"],["nacer","태어나다","동사"],["perder","잃다","동사 (e→ie)"],["despertar","깨우다","동사 (e→ie)"],
["morir","죽다","동사 (o→ue)"],["decir","말하다","동사 (e→i)"],["repetir","반복하다","동사 (e→i)"],["servir","봉사하다","동사 (e→i)"],["elegir","고르다","동사 (e→i)"],
["recibir","받다","동사"],["enviar","보내다","동사"],["guardar","보관하다","동사"],["invitar","초대하다","동사"],["visitar","방문하다","동사"]
],
3: [
["grande","큰","형용사"],["pequeño","작은","형용사"],["nuevo","새로운","형용사"],["viejo","낡은, 늙은","형용사"],["joven","젊은","형용사"],
["bueno","좋은","형용사"],["malo","나쁜","형용사"],["bonito","예쁜","형용사"],["feo","못생긴","형용사"],["alto","키 큰, 높은","형용사"],
["bajo","키 작은, 낮은","형용사"],["largo","긴","형용사"],["corto","짧은","형용사"],["fuerte","강한","형용사"],["débil","약한","형용사"],
["caro","비싼","형용사"],["barato","싼","형용사"],["limpio","깨끗한","형용사"],["sucio","더러운","형용사"],["lleno","가득 찬","형용사"],
["vacío","텅 빈","형용사"],["frío","차가운","형용사"],["caliente","뜨거운","형용사"],["feliz","행복한","형용사"],["triste","슬픈","형용사"],
["enfermo","아픈","형용사"],["ocupado","바쁜","형용사"],["libre","자유로운, 한가한","형용사"],["listo","준비된, 똑똑한","형용사"],["seguro","확실한, 안전한","형용사"],
["siempre","항상","부사"],["nunca","결코 ~않다","부사"],["ahora","지금","부사"],["luego","나중에","부사"],["temprano","일찍","부사"],
["tarde","늦게, 오후","부사"],["hoy","오늘","부사"],["ayer","어제","부사"],["todavía","아직","부사"],["ya","이미, 벌써","부사"],
["mucho","많이","부사"],["poco","조금","부사"],["bastante","꽤, 충분히","부사"],["demasiado","너무 많이","부사"],["casi","거의","부사"],
["quizás","아마도","부사"],["juntos","함께","부사"],["afuera","밖에","부사"],["adentro","안에","부사"],["despacio","천천히","부사"],
["ancho","넓은","형용사"],["estrecho","좁은","형용사"],["delgado","마른","형용사"],["lento","느린","형용사"],["seco","마른, 건조한","형용사"],
["mojado","젖은","형용사"],["claro","밝은, 분명한","형용사"],["oscuro","어두운","형용사"],["blanco","흰","형용사"],["negro","검은","형용사"],
["rojo","빨간","형용사"],["verde","초록의","형용사"],["alegre","즐거운","형용사"],["contento","만족한","형용사"],["rico","부유한, 맛있는","형용사"],
["pobre","가난한","형용사"],["amable","친절한","형용사"],["tranquilo","조용한","형용사"],["nervioso","긴장한","형용사"],["valiente","용감한","형용사"],
["sano","건강한","형용사"],["dulce","달콤한","형용사"],["amargo","쓴","형용사"],["salado","짠","형용사"],["duro","단단한","형용사"],
["ligero","가벼운","형용사"],["pesado","무거운","형용사"],["profundo","깊은","형용사"],["cercano","가까운","형용사"],["lejano","먼","형용사"],
["primero","첫 번째의","형용사"],["verdadero","진짜의","형용사"],["aquí","여기","부사"],["allí","저기","부사"],["cerca","가까이","부사"],
["lejos","멀리","부사"],["bien","잘","부사"],["mejor","더 좋게","부사"],["peor","더 나쁘게","부사"],["también","또한","부사"],
["pronto","곧","부사"],["arriba","위에","부사"],["abajo","아래에","부사"],["dentro","안에","부사"],["fuera","밖에","부사"],
["detrás","뒤에","부사"],["gordo","뚱뚱한","형용사"],["suave","부드러운","형용사"],["áspero","거친","형용사"],["amarillo","노란","형용사"]
],
4: [
["hospital","병원","el (남성)"],["farmacia","약국","la (여성)"],["biblioteca","도서관","la (여성)"],["banco","은행, 벤치","el (남성)"],["oficina","사무실","la (여성)"],
["parque","공원","el (남성)"],["museo","박물관","el (남성)"],["iglesia","교회","la (여성)"],["restaurante","식당","el (남성)"],["hotel","호텔","el (남성)"],
["aeropuerto","공항","el (남성)"],["puerto","항구","el (남성)"],["pueblo","마을","el (남성)"],["campo","시골, 들판","el (남성)"],["montaña","산","la (여성)"],
["río","강","el (남성)"],["mar","바다","el (남성)"],["isla","섬","la (여성)"],["bosque","숲","el (남성)"],["cielo","하늘","el (남성)"],
["médico","의사","el (남성)"],["enfermera","간호사","la (여성)"],["profesor","교수, 선생님","el (남성)"],["abogado","변호사","el (남성)"],["ingeniero","엔지니어","el (남성)"],
["cocinero","요리사","el (남성)"],["camarero","웨이터","el (남성)"],["policía","경찰","el/la (공통)"],["cliente","손님","el (남성)"],["jefe","상사, 사장","el (남성)"],
["sueldo","급여, 월급","el (남성)"],["precio","가격","el (남성)"],["cuenta","계산서, 계좌","la (여성)"],["tarjeta","카드","la (여성)"],["billete","표, 지폐","el (남성)"],
["maleta","여행가방","la (여성)"],["viaje","여행","el (남성)"],["fiesta","파티, 축제","la (여성)"],["regalo","선물","el (남성)"],["problema","문제","el (예외: 남성명사)"],
["idea","생각","la (여성)"],["tiempo","시간, 날씨","el (남성)"],["semana","주(週)","la (여성)"],["mes","달(月)","el (남성)"],["año","해(年)","el (남성)"],
["hora","시간(時)","la (여성)"],["momento","순간","el (남성)"],["vida","삶","la (여성)"],["mundo","세계","el (남성)"],["empresa","회사","la (여성)"],
["gobierno","정부","el (남성)"],["sociedad","사회","la (여성)"],["cultura","문화","la (여성)"],["ciencia","과학","la (여성)"],["examen","시험","el (남성)"],
["curso","과정","el (남성)"],["clase","수업","la (여성)"],["universidad","대학","la (여성)"],["medicina","약, 의학","la (여성)"],["salud","건강","la (여성)"],
["enfermedad","병","la (여성)"],["dolor","고통","el (남성)"],["cuerpo","몸","el (남성)"],["mente","정신","la (여성)"],["esfuerzo","노력","el (남성)"],
["negocio","사업","el (남성)"],["producto","제품","el (남성)"],["servicio","서비스","el (남성)"],["calidad","품질","la (여성)"],["cantidad","양","la (여성)"],
["factura","청구서","la (여성)"],["compra","구매","la (여성)"],["venta","판매","la (여성)"],["reunión","회의","la (여성)"],["proyecto","프로젝트","el (남성)"],
["plan","계획","el (남성)"],["resultado","결과","el (남성)"],["causa","원인","la (여성)"],["efecto","효과","el (남성)"],["ejemplo","예","el (남성)"],
["detalle","세부사항","el (남성)"],["tema","주제","el (예외: 남성명사)"],["programa","프로그램","el (예외: 남성명사)"],["sistema","체계","el (예외: 남성명사)"],["idioma","언어","el (예외: 남성명사)"],
["método","방법","el (남성)"],["forma","형태","la (여성)"],["manera","방식","la (여성)"],["costumbre","관습","la (여성)"],["boda","결혼식","la (여성)"],
["vuelo","비행","el (남성)"],["pasaporte","여권","el (남성)"],["frontera","국경","la (여성)"],["extranjero","외국인, 외국의","el (남성)"],["frase","문장","la (여성)"],
["noticia","소식","la (여성)"],["periódico","신문","el (남성)"],["revista","잡지","la (여성)"],["anuncio","광고","el (남성)"],["imagen","이미지","la (여성)"]
],
5: [
["música","음악","la (여성)"],["película","영화","la (여성)"],["teléfono","전화","el (남성)"],["jardín","정원","el (남성)"],["estación","역, 계절","la (여성)"],
["canción","노래","la (여성)"],["habitación","방","la (여성)"],["información","정보","la (여성)"],["avión","비행기","el (남성)"],["mañana","아침, 내일","la (여성)"],
["compañero","동료, 친구","el (남성)"],["cumpleaños","생일","el (남성)"],["difícil","어려운","형용사"],["fácil","쉬운","형용사"],["rápido","빠른","형용사"],
["último","마지막의","형용사"],["próximo","다음의","형용사"],["cansado","피곤한","형용사"],["café","커피","el (남성)"],["árbol","나무","el (남성)"],
["azúcar","설탕","el (남성)"],["lápiz","연필","el (남성)"],["papá","아빠","el (남성)"],["mamá","엄마","la (여성)"],["niño","아이","el (남성)"],
["señor","(남성) ~씨","el (남성)"],["señora","(여성) ~씨","la (여성)"],["baño","화장실, 욕실","el (남성)"],["sueño","꿈, 졸음","el (남성)"],["otoño","가을","el (남성)"],
["número","숫자","el (남성)"],["página","페이지","la (여성)"],["médica","여의사","la (여성)"],["práctica","연습","la (여성)"],["fábrica","공장","la (여성)"],
["máquina","기계","la (여성)"],["plátano","바나나","el (남성)"],["jamón","햄","el (남성)"],["limón","레몬","el (남성)"],["melón","멜론","el (남성)"],
["corazón","심장, 마음","el (남성)"],["razón","이유","la (여성)"],["camión","트럭","el (남성)"],["televisión","텔레비전","la (여성)"],["dirección","주소, 방향","la (여성)"],
["explicación","설명","la (여성)"],["conversación","대화","la (여성)"],["educación","교육","la (여성)"],["atención","주의, 관심","la (여성)"],["intención","의도","la (여성)"],
["situación","상황","la (여성)"],["población","인구","la (여성)"],["relación","관계","la (여성)"],["condición","조건","la (여성)"],["decisión","결정","la (여성)"],
["discusión","토론","la (여성)"],["opinión","의견","la (여성)"],["expresión","표현","la (여성)"],["impresión","인상","la (여성)"],["presión","압력","la (여성)"],
["tensión","긴장","la (여성)"],["pasión","열정","la (여성)"],["creación","창조","la (여성)"],["generación","세대","la (여성)"],["tradición","전통","la (여성)"],
["organización","조직","la (여성)"],["comunicación","의사소통","la (여성)"],["participación","참여","la (여성)"],["investigación","연구","la (여성)"],["celebración","축하","la (여성)"],
["imaginación","상상","la (여성)"],["preocupación","걱정","la (여성)"],["satisfacción","만족","la (여성)"],["construcción","건설","la (여성)"],["producción","생산","la (여성)"],
["protección","보호","la (여성)"],["destrucción","파괴","la (여성)"],["evolución","진화","la (여성)"],["revolución","혁명","la (여성)"],["solución","해결책","la (여성)"],
["institución","기관","la (여성)"],["conocimiento","지식","el (남성)"],["pensamiento","사고","el (남성)"],["sentimiento","감정","el (남성)"],["comportamiento","행동","el (남성)"],
["desarrollo","발전","el (남성)"],["crecimiento","성장","el (남성)"],["esperanza","희망","la (여성)"],["confianza","신뢰","la (여성)"],["paciencia","인내","la (여성)"],
["experiencia","경험","la (여성)"],["conciencia","양심, 의식","la (여성)"],["influencia","영향","la (여성)"],["importancia","중요성","la (여성)"],["diferencia","차이","la (여성)"],
["consecuencia","결과","la (여성)"],["increíble","믿을 수 없는","형용사"],["imposible","불가능한","형용사"],["posible","가능한","형용사"],["necesario","필요한","형용사"]
]
};
